services:
  OxidEsales\EshopCommunity\Internal\Templating\TemplateEngineBridge:
    class: OxidEsales\EshopCommunity\Internal\Templating\TemplateEngineBridge
    arguments:
        $templateEngine: '@OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine'
    public: true