services:
  OxidEsales\Eshop\Core\Config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', getConfig]
    public: false

  OxidEsales\Eshop\Core\UtilsView:
    class: OxidEsales\Eshop\Core\UtilsView
    factory: ['OxidEsales\Eshop\Core\Registry', getUtilsView]
    public: false

  OxidEsales\EshopCommunity\Internal\Smarty\SmartyContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyContext
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Smarty\TemplateEngineConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngineConfiguration
    arguments:
        - '@OxidEsales\EshopCommunity\Internal\Smarty\SmartyContextInterface'
    public: false

  OxidEsales\EshopCommunity\Internal\Smarty\SmartyFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyFactory
    autowire: true
    public: false

  Smarty:
    class: Smarty
    factory: 'OxidEsales\EshopCommunity\Internal\Smarty\SmartyFactoryInterface:getSmarty'
    public: false

  Symfony\Component\Templating\TemplateNameParserInterface:
    class: Symfony\Component\Templating\TemplateNameParser
    public: true

  OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine
    autowire: true
    public: false
